import { Title } from '@/types/domain';

export const VIBE_CHIPS = [
  'slow-burn',
  'high-stakes',
  'comfort',
  'mind-bending',
  'dark-humor',
  'feel-good',
  'cozy-mystery',
  'adrenaline',
  'epic',
  'thoughtful',
] as const;

export const GENRES = [
  'Drama',
  'Thriller',
  'Sci-Fi',
  'Comedy',
  'Action',
  'Mystery',
  'Fantasy',
  'Romance',
  'Crime',
  'Animation',
] as const;

export const TITLES: Title[] = [
  {
    id: 't1',
    title_name: 'Severance',
    year: 2022,
    genres: ['Drama', 'Sci-Fi', 'Mystery'],
    runtime: 50,
    language: 'en',
    moods: ['slow-burn', 'mind-bending', 'thoughtful'],
    popularity: 89,
    synopsis:
      'Office workers split memories between work and personal lives, revealing a deeply unsettling corporate secret.',
    cast: ['Adam Scott', 'Britt Lower', 'Patricia Arquette'],
    poster_url: 'https://image.tmdb.org/t/p/w500/severance.jpg',
    availability_hint: 'Likely on Apple TV+',
  },
  {
    id: 't2',
    title_name: 'The Bear',
    year: 2022,
    genres: ['Drama', 'Comedy'],
    runtime: 35,
    language: 'en',
    moods: ['high-stakes', 'comfort', 'thoughtful'],
    popularity: 91,
    synopsis:
      'A chef returns home to save his family sandwich shop while juggling grief, chaos, and ambition.',
    cast: ['Jeremy Allen White', 'Ayo Edebiri', 'Ebon Moss-Bachrach'],
    poster_url: 'https://image.tmdb.org/t/p/w500/thebear.jpg',
    availability_hint: 'Likely on Hulu',
  },
  {
    id: 't3',
    title_name: 'Dune: Part Two',
    year: 2024,
    genres: ['Sci-Fi', 'Action', 'Drama'],
    runtime: 166,
    language: 'en',
    moods: ['epic', 'high-stakes', 'adrenaline'],
    popularity: 96,
    synopsis:
      'Paul Atreides seeks vengeance while rising as a messianic leader among the Fremen.',
    cast: ['Timothee Chalamet', 'Zendaya', 'Rebecca Ferguson'],
    poster_url: 'https://image.tmdb.org/t/p/w500/dune2.jpg',
    availability_hint: 'Likely on Max',
  },
  {
    id: 't4',
    title_name: 'Knives Out',
    year: 2019,
    genres: ['Mystery', 'Comedy', 'Crime'],
    runtime: 130,
    language: 'en',
    moods: ['cozy-mystery', 'dark-humor', 'comfort'],
    popularity: 88,
    synopsis:
      'A detective investigates the death of a wealthy novelist and uncovers family secrets.',
    cast: ['Daniel Craig', 'Ana de Armas', 'Chris Evans'],
    poster_url: 'https://image.tmdb.org/t/p/w500/knivesout.jpg',
    availability_hint: 'Likely on Prime Video',
  },
  {
    id: 't5',
    title_name: 'The Last of Us',
    year: 2023,
    genres: ['Drama', 'Action'],
    runtime: 58,
    language: 'en',
    moods: ['high-stakes', 'thoughtful', 'slow-burn'],
    popularity: 94,
    synopsis:
      'A hardened survivor escorts a teenage girl across a post-apocalyptic United States.',
    cast: ['Pedro Pascal', 'Bella Ramsey', 'Anna Torv'],
    poster_url: 'https://image.tmdb.org/t/p/w500/lastofus.jpg',
    availability_hint: 'Likely on Max',
  },
  {
    id: 't6',
    title_name: 'Past Lives',
    year: 2023,
    genres: ['Drama', 'Romance'],
    runtime: 106,
    language: 'en',
    moods: ['thoughtful', 'slow-burn', 'comfort'],
    popularity: 79,
    synopsis:
      'Two childhood friends reconnect decades later and confront destiny, love, and migration.',
    cast: ['Greta Lee', 'Teo Yoo', 'John Magaro'],
    poster_url: 'https://image.tmdb.org/t/p/w500/pastlives.jpg',
    availability_hint: 'Likely on Paramount+ with Showtime',
  },
  {
    id: 't7',
    title_name: 'Silo',
    year: 2023,
    genres: ['Sci-Fi', 'Mystery', 'Drama'],
    runtime: 49,
    language: 'en',
    moods: ['slow-burn', 'mind-bending', 'high-stakes'],
    popularity: 86,
    synopsis:
      'Residents of an underground bunker investigate the truth behind their isolated world.',
    cast: ['Rebecca Ferguson', 'Common', 'David Oyelowo'],
    poster_url: 'https://image.tmdb.org/t/p/w500/silo.jpg',
    availability_hint: 'Likely on Apple TV+',
  },
  {
    id: 't8',
    title_name: 'The Menu',
    year: 2022,
    genres: ['Thriller', 'Comedy', 'Mystery'],
    runtime: 107,
    language: 'en',
    moods: ['dark-humor', 'high-stakes', 'thoughtful'],
    popularity: 82,
    synopsis:
      'Guests at an exclusive dining experience discover a disturbing surprise curated by a celebrity chef.',
    cast: ['Anya Taylor-Joy', 'Ralph Fiennes', 'Nicholas Hoult'],
    poster_url: 'https://image.tmdb.org/t/p/w500/themenu.jpg',
    availability_hint: 'Likely on Hulu',
  },
  {
    id: 't9',
    title_name: 'Ted Lasso',
    year: 2020,
    genres: ['Comedy', 'Drama'],
    runtime: 34,
    language: 'en',
    moods: ['feel-good', 'comfort', 'thoughtful'],
    popularity: 90,
    synopsis:
      'An optimistic American coach leads a struggling English soccer team with empathy and humor.',
    cast: ['Jason Sudeikis', 'Hannah Waddingham', 'Brett Goldstein'],
    poster_url: 'https://image.tmdb.org/t/p/w500/tedlasso.jpg',
    availability_hint: 'Likely on Apple TV+',
  },
  {
    id: 't10',
    title_name: 'Andor',
    year: 2022,
    genres: ['Sci-Fi', 'Drama', 'Action'],
    runtime: 45,
    language: 'en',
    moods: ['high-stakes', 'thoughtful', 'slow-burn'],
    popularity: 87,
    synopsis:
      'Cassian Andor becomes a key figure in the early rebellion against the Empire.',
    cast: ['Diego Luna', 'Stellan Skarsgard', 'Genevieve OReilly'],
    poster_url: 'https://image.tmdb.org/t/p/w500/andor.jpg',
    availability_hint: 'Likely on Disney+',
  },
  {
    id: 't11',
    title_name: 'Arcane',
    year: 2021,
    genres: ['Animation', 'Action', 'Drama'],
    runtime: 42,
    language: 'en',
    moods: ['high-stakes', 'adrenaline', 'thoughtful'],
    popularity: 92,
    synopsis:
      'Two sisters are pulled to opposite sides of a conflict between progress and rebellion.',
    cast: ['Hailee Steinfeld', 'Ella Purnell', 'Katie Leung'],
    poster_url: 'https://image.tmdb.org/t/p/w500/arcane.jpg',
    availability_hint: 'Likely on Netflix',
  },
  {
    id: 't12',
    title_name: 'Only Murders in the Building',
    year: 2021,
    genres: ['Comedy', 'Mystery', 'Crime'],
    runtime: 33,
    language: 'en',
    moods: ['cozy-mystery', 'comfort', 'dark-humor'],
    popularity: 84,
    synopsis:
      'Three true-crime obsessed neighbors start their own podcast while solving murders in their building.',
    cast: ['Steve Martin', 'Martin Short', 'Selena Gomez'],
    poster_url: 'https://image.tmdb.org/t/p/w500/onlymurders.jpg',
    availability_hint: 'Likely on Hulu',
  },
  {
    id: 't13',
    title_name: 'Spider-Man: Across the Spider-Verse',
    year: 2023,
    genres: ['Animation', 'Action', 'Sci-Fi'],
    runtime: 140,
    language: 'en',
    moods: ['epic', 'adrenaline', 'mind-bending'],
    popularity: 95,
    synopsis:
      'Miles Morales crosses dimensions and clashes with a new Spider-team over the fate of the multiverse.',
    cast: ['Shameik Moore', 'Hailee Steinfeld', 'Oscar Isaac'],
    poster_url: 'https://image.tmdb.org/t/p/w500/spiderverse.jpg',
    availability_hint: 'Likely on Netflix',
  },
  {
    id: 't14',
    title_name: 'The Night Agent',
    year: 2023,
    genres: ['Action', 'Thriller', 'Drama'],
    runtime: 47,
    language: 'en',
    moods: ['high-stakes', 'adrenaline', 'comfort'],
    popularity: 83,
    synopsis:
      'An FBI agent answers a mysterious hotline call and gets pulled into a conspiracy.',
    cast: ['Gabriel Basso', 'Luciane Buchanan', 'Hong Chau'],
    poster_url: 'https://image.tmdb.org/t/p/w500/nightagent.jpg',
    availability_hint: 'Likely on Netflix',
  },
  {
    id: 't15',
    title_name: 'Everything Everywhere All at Once',
    year: 2022,
    genres: ['Sci-Fi', 'Comedy', 'Action'],
    runtime: 139,
    language: 'en',
    moods: ['mind-bending', 'adrenaline', 'thoughtful'],
    popularity: 93,
    synopsis:
      'A laundromat owner is recruited to save reality while confronting fractured versions of her life.',
    cast: ['Michelle Yeoh', 'Ke Huy Quan', 'Stephanie Hsu'],
    poster_url: 'https://image.tmdb.org/t/p/w500/everything.jpg',
    availability_hint: 'Likely on Paramount+',
  },
  {
    id: 't16',
    title_name: 'Poker Face',
    year: 2023,
    genres: ['Mystery', 'Comedy', 'Crime'],
    runtime: 52,
    language: 'en',
    moods: ['cozy-mystery', 'comfort', 'thoughtful'],
    popularity: 80,
    synopsis:
      'A woman with a gift for detecting lies solves unusual crimes while on the run.',
    cast: ['Natasha Lyonne', 'Benjamin Bratt', 'Adrien Brody'],
    poster_url: 'https://image.tmdb.org/t/p/w500/pokerface.jpg',
    availability_hint: 'Likely on Peacock',
  },
  {
    id: 't17',
    title_name: 'House of the Dragon',
    year: 2022,
    genres: ['Fantasy', 'Drama', 'Action'],
    runtime: 61,
    language: 'en',
    moods: ['epic', 'high-stakes', 'dark-humor'],
    popularity: 90,
    synopsis: 'A dynastic struggle for the Iron Throne tears a ruling family apart.',
    cast: ['Emma DArcy', 'Matt Smith', 'Olivia Cooke'],
    poster_url: 'https://image.tmdb.org/t/p/w500/hotd.jpg',
    availability_hint: 'Likely on Max',
  },
  {
    id: 't18',
    title_name: 'A Real Pain',
    year: 2024,
    genres: ['Drama', 'Comedy'],
    runtime: 95,
    language: 'en',
    moods: ['thoughtful', 'comfort', 'dark-humor'],
    popularity: 68,
    synopsis:
      'Two cousins reconnect on a memorial trip through Poland with old tensions resurfacing.',
    cast: ['Jesse Eisenberg', 'Kieran Culkin', 'Will Sharpe'],
    poster_url: 'https://image.tmdb.org/t/p/w500/realpain.jpg',
    availability_hint: 'Likely theatrical or PVOD',
  },
  {
    id: 't19',
    title_name: 'Blue Eye Samurai',
    year: 2023,
    genres: ['Animation', 'Action', 'Drama'],
    runtime: 46,
    language: 'en',
    moods: ['adrenaline', 'high-stakes', 'slow-burn'],
    popularity: 85,
    synopsis:
      'A mixed-race swordswoman in Edo-period Japan seeks vengeance while hiding her identity.',
    cast: ['Maya Erskine', 'Masi Oka', 'Brenda Song'],
    poster_url: 'https://image.tmdb.org/t/p/w500/blueeyesamurai.jpg',
    availability_hint: 'Likely on Netflix',
  },
  {
    id: 't20',
    title_name: 'The Gentlemen',
    year: 2024,
    genres: ['Crime', 'Comedy', 'Action'],
    runtime: 55,
    language: 'en',
    moods: ['dark-humor', 'high-stakes', 'adrenaline'],
    popularity: 81,
    synopsis:
      'An aristocrat inherits a criminal empire and must outmaneuver dangerous rivals.',
    cast: ['Theo James', 'Kaya Scodelario', 'Giancarlo Esposito'],
    poster_url: 'https://image.tmdb.org/t/p/w500/gentlemen.jpg',
    availability_hint: 'Likely on Netflix',
  },
];
