const baseTheme = {
  colors: {
    background: '#0E1218',
    backgroundAlt: '#131A23',
    surface: '#18212C',
    surfaceStrong: '#202C39',
    surfaceElevated: '#283645',
    text: '#F5EFE3',
    textMuted: '#CDC2B1',
    accent: '#D07D3D',
    accentAlt: '#6BA9E6',
    border: '#334557',
    danger: '#D96F63',
    success: '#6FC7A4',
    onAccent: '#0F141B',
  },
  type: {
    family: {
      display: 'PlayfairDisplay-Bold',
      body: 'SourceSans3-Regular',
      bodyStrong: 'SourceSans3-SemiBold',
    },
    size: {
      xs: 12,
      sm: 14,
      md: 16,
      lg: 18,
      xl: 22,
      xxl: 30,
    },
    lineHeight: {
      xs: 16,
      sm: 20,
      md: 24,
      lg: 27,
      xl: 31,
      xxl: 38,
    },
  },
  space: {
    xs: 6,
    sm: 10,
    md: 14,
    lg: 20,
    xl: 28,
    xxl: 36,
  },
  radius: {
    sm: 10,
    md: 14,
    lg: 18,
    pill: 999,
  },
  stroke: {
    thin: 1,
    regular: 1.5,
  },
  motion: {
    fast: 120,
    normal: 220,
    slow: 320,
  },
};

export const VibeTheme = {
  ...baseTheme,
  bg: baseTheme.colors.background,
  panel: baseTheme.colors.surface,
  panelStrong: baseTheme.colors.surfaceStrong,
  text: baseTheme.colors.text,
  textMuted: baseTheme.colors.textMuted,
  accent: baseTheme.colors.accent,
  accentAlt: baseTheme.colors.accentAlt,
  border: baseTheme.colors.border,
  danger: baseTheme.colors.danger,
};
